### ISSUE TITLE
shortcuts in FileTree not working correctly

### ISSUE THREAD

**Issue by rcoreilly** [goki/gi#244]
I tried Ctrl+I on a directory to add a file to that dir, and it said something about not being able to add files to directories..

Then I clicked on a file within the dir and did Ctrl+I again and it apparently overwrote that file with a blank file!!! yikes that is not good!  it should just pull up the prompt for a new file name in all cases.  fortunately I hadn't edited that particular file..

**Comment by rohrlich** [comment]
I reproduced the first of the issues. I'll take a look.

**Comment by rohrlich** [comment]
-- The "Add to Git" should be resolved now
-- Also ctrl+0 was falling into correct case but calling NewFile (fixed)
---------------------------------------------------------------------------
Remaining Issue!
- I tried Ctrl+I on a directory to add a file to that dir, and it said something about not being able to add files to directories..
** You get this message because the enter filename dialog is not invoked as it is when you use the ctxt menu so when you join dir and filename you only get the dir part.
What I know:
 -- the FileTreeView NewFile/Folder funcs are calling FileNode::NewFile/Folder directly, not using CallMethod but switching to CallMethod caused the dialog to appear twice.
-- I removed the arg from the menu properties and that works but then you get the dialog twice if you use the ctxt menu.
-- removing the call methods and leaving the arg on the menu property didn't resolve the problem either
-- I tried other combinations of calling directly and using CallMethod but none worked for both key and menu.
-- Would be good if we could just use the CallMethod or the props and not have both.
-- And of course I could just open the dialog manually from the FileTreeView::FileName code

**Comment by rohrlich** [comment]
Did not mean to bold those lines!

**Comment by rcoreilly** [comment]
key principles:
- CallMethod pops up a dialog. Calling directly does not.
- Context menu from props automatically uses equivalent of CallMethod -- thus when you invoke FileTree::NewFile from context menu, it pops up dialog.
- So, in this case, the KeyInput method needed CallMethod, and that's it -- the FileTree gets its own args and passes those to filenode so you don't want to use CallMethod in FileTree calling FileNode.  If FileTree didn't already prompt for the args, then you could use CallMethod there..

**Comment by rohrlich** [comment]
boy am i dumb!
