### ISSUE TITLE
Hardcoded paths

### ISSUE THREAD

**Issue by pztrn** [goki/gi#272]
There are hardcoded fonts paths in X11 driver. For example, on Archlinux truetype fonts are installed in /usr/share/fonts/TTF, not /usr/share/fonts/truetype. Also there is per-user ``~/.fonts`` that can also contain some fonts to use.

Also I've received this message while executing go run:

```
2019/05/04 07:42:51 kit.GoSrcDir: unable to locate directory ("github.com/goki/gi/icons") in GOPATH/src/ ("/data/gopath") or GOROOT/src/pkg/ ("")
```

Which just isn't right because in that case you should use something like https://github.com/UnnoTed/fileb0x to embed icons into Go code as separate package. Looks like due to that error OpenGL context isn't initialized properly and my application isn't working.

**Comment by rcoreilly** [comment]
Thanks for the tip for file embedding -- will definitely need to get that done and if you have any experience and could contribute at PR that would be great!

Those initial font prefs can be overwritten in the GoGi Prefs panel, FontPaths, so you can add / fix etc there.

I don't think either is going to be the source of the openGL issues which may either have been fixed by now due to a lot of updates I've been doing, or are due to your driver not being sufficiently up-to-date, or something else.  anyway if you can include any output that might help diagnose.

**Comment by rcoreilly** [comment]
finally fixed embedding of icons.
