### ISSUE TITLE
Large slices slow to display

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#275]

**Comment by rcoreilly** [comment]
surprisingly many issues here!  in the course of tracking this down:

* ki Tree traversal sped up by 10x by using non-recursive methods
* ki: better documented *Fast ways of adding elements, and cleaned that code up significantly (wasn't an issue here as we were using SetChild which is VERY fast.. though there were still a few minor things)
*  copying icons was very slow -- now have hand-written 10x faster copying of gi nodes

more details here:
https://docs.google.com/spreadsheets/d/1WWorjrVao6sLRuwKguyRnnuY51DxsZOpokZHzGtmnbE/edit?usp=sharing

but wait, there's more!  still major slowness present and will keep tracking it down..

**Comment by rohrlich** [comment]
Slice display much better and overall everything feels “snappier”, but yes still some slowness in slice display.

- John


On May 18, 2019, at 1:37 AM, rcoreilly <notifications@github.com<mailto:notifications@github.com>> wrote:


surprisingly many issues here! in the course of tracking this down:

  *   ki Tree traversal sped up by 10x by using non-recursive methods
  *   ki: better documented *Fast ways of adding elements, and cleaned that code up significantly (wasn't an issue here as we were using SetChild which is VERY fast.. though there were still a few minor things)
  *   copying icons was very slow -- now have hand-written 10x faster copying of gi nodes

more details here:
https://docs.google.com/spreadsheets/d/1WWorjrVao6sLRuwKguyRnnuY51DxsZOpokZHzGtmnbE/edit?usp=sharing

but wait, there's more! still major slowness present and will keep tracking it down..

**Comment by rcoreilly** [comment]
Much of the rest of the time was expensive styling operations redundantly applied repeatedly on each element -- now caching that using a Template name that views set, and which widgets propagate appropriately to their sub-parts (otherwise it has limited benefits).  really are a ton of parts by the time it all gets rendered out, so even small ops repeated so many times really adds up.

opening time on the gi/examples/views SliceTest button is now reasonable, even for 10k elements in the slice, and rendering speed remains quite good.  now just need to fix the editing speed.

**Comment by rohrlich** [comment]
The slice test in the latest "checked in" code has 2880 items and the time to display/scroll is about 4 seconds. My 3640 item slice is 5 seconds so that make sense. My slice of 26496 takes 35 seconds which is a pretty linear result. I don't actually need to look at a slice that large but when we have an etensor viewer I might.

**Comment by rcoreilly** [comment]
I added precise elapsed time timing and now am down to 1.8 sec for initial render -- added back 2nd full render which gets focus working and ensures dynamic sizing is better, but that 1.8 is comparable.
6 sec for 10k.

even though this has done great things for finding all the major bottlenecks in rendering, it probably does still make sense to add a smarter logic for these things -- it is kinda crazy to be rendering all this stuff instead of just re-using only visible widgets and scrolling those in data space instead of gui space...

**Comment by rohrlich** [comment]
Having a window over the data will probably be a pain to implement but it would certainly make it much faster and probably is what needs to be done.

**Comment by rohrlich** [comment]
Not slow anymore!!!
