### ISSUE TITLE
Undo (and redo) sometimes creates errors in gide

### ISSUE THREAD

**Issue by kplat1** [goki/gi#322]

**Comment by rcoreilly** [comment]
just did a lot of through tests -- and it is very rare when it seems to breakdown in my experience -- will need some reliable replicable cases to fix this unfortunately.

**Comment by rcoreilly** [comment]
Ahah!  finally caught the bug in action.  The problem arises when you add some code that then ends up through goimport  adding a package at the top of the file.  Then any undo going back prior to that addition will be off, until the import goes away.  So in particular you can never undo the line that caused the import because it will be off..

More generally, any auto-format changes caused by go import will also not be registered.

So, the clear answer is that any changes made by go import must be registered with undo!  This is not so bad because we use diffs anyway, so it is all just edits.

But we seriously then need to batch the undos, which is another ticket -- not so hard.

**Comment by rcoreilly** [comment]
new rewrite seems solid in current testing.  and batching is in place.  leaving this open pending more testing but hopefully fixed.

**Comment by rcoreilly** [comment]
seems good -- reopen / refile if new issue (hopefully with specific replicability)
