### ISSUE TITLE
focus not leaving text field

### ISSUE THREAD

**Issue by rohrlich** [goki/gi#37]
If I click in text field (also spin text field) and then click on combo or slider, etc. and then type a character it goes into the previously focused text field. I suppose you could have designed it this way?

When I then do Command-Q to quit the Widgets demo a 'q' appears in text field and the app doesn't close.

**Comment by rcoreilly** [comment]
Yep, the current design works like that, intentionally.  Specifically, buttons do not call GrabFocus when they are clicked, but textfields do.  So textfields keep the text input focus despite clicks.  Could easily change that -- tried a quick search for accepted practice and didn't find much.  This may have something, but I couldn't see it:
https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/focus-overview

It does have the distinction between "logical" and "keyboard" focus -- the text edit could lose "active" keyboard focus but still retain the "logical" focus so if you went back to it, it would get it back.. not sure.  anyway, all this stuff is relatively easy to change.

for reference, in emergent, everything loses focus when buttons are clicked because of the redraw process.  ValueView has a more immediate apply logic, so it doesn't have that behavior..

maybe see how it goes in practice?  definitely some negative side effects but also possible benefits of keeping focus.. could

**Comment by rcoreilly** [comment]
I implemented the active focus logic -- seems pretty good to me..  currently, keyboard input events still trigger the re-activation of a de-activated text field, so typing does go in there, but in the mean-time the edit is applied (fixing #46 and one of the main pain-points here), and the field is styled as inactive (but retains the cursor :)

the Command-Q problem is a separate issue that I will fix now -- no keys accepted that have modifiers other than shift or alt.. ctrl or meta never means "add a key".

let me know what you think of the current behavior..

**Comment by rcoreilly** [comment]
@thazy looping Tom in here too theoretically..

**Comment by rcoreilly** [comment]
overall this is looking good to me -- closing.  reopen with specific issues.
