### ISSUE TITLE
Tab frames are inheriting scrollbars from larger tabs, even if not needed.

### ISSUE THREAD

**Issue by kplat1** [goki/gi#371]

**Comment by rcoreilly** [comment]
this is quite possibly fixed -- there were a few issues there that are now fixed with the flow layout -- could have fixed this too -- it looked a lot better to me for gide tabs.

**Comment by rcoreilly** [comment]
actually, there are two different cases: if a tab has a strong minimum size, then all tabs will get that same minimum size, because it uses a "stacked layout" and that is what it does.  changing that would break a lot of other things. and it makes sure tabs all fit in the same space -- this is a kind of side-effect of that.

but previously we might have had *further* issues with aberrant scrollbars that might be fixed now (also with scrollbars missing).

**Comment by rcoreilly** [comment]
I just changed the Layout code for Stacked case to only use the top widget -- actually it works well and doesn't seem to break anything so far!  give it a try..
