### ISSUE TITLE
Gi3D 2D Text positioning is different from the positioning of other objects

### ISSUE THREAD

**Issue by kplat1** [goki/gi#372]
When you set the position of Gi3D 2D Text, it sets the text to start at that position. For every other 3D object, it sets the center of where the object goes, not the start. Having it be different for 2D Text is inconsistent and confusing.

**Comment by rcoreilly** [comment]
set text-align or horizontal-align or whatever the right thing is, to "Center" and it will behave like other objects.  I just happens to default to left aligned.

**Comment by kplat1** [comment]
The default should be center, like everything else.

**Comment by kplat1** [comment]
Also, even when I set text-align or horizontal-align, it doesn't work.

**Comment by rcoreilly** [comment]
I am not going to change the default because this is deep in gi style and has an existing default that is consistent with 2D, and is very easily changed.  It is definitely working as tested in both gi3d and your code, which had it being set in two places and you probably only changed one to test.. :)
