### ISSUE TITLE
Scrollbar in font selector window disappears

### ISSUE THREAD

**Issue by thazy** [goki/gi#87]
In GoGi Preferences -> FontFamily/Go -> font selector:  attempt at two finger horizontal scroll causes scrollbar at bottom to disappear.  Thus, had no way to scroll to right to see additional columns.  Discovered that clicking in any of the column headers (Name, Stretch, etc.) brought the scrollbar back and then I could use it.  Is there a reason not to have two-finger horizontal scroll or something similar? (Two-finger vertical scroll works as expected.)

![img_0162](https://user-images.githubusercontent.com/30027010/44674604-47188c80-a9eb-11e8-8cfb-2e9a51b18cda.JPG)

**Comment by rcoreilly** [comment]
this is tricky, because the two scrollbars are on different layouts, and the deeper one is the vertical and it was capturing the entire scroll event, so the upper horizontal didn't get anything.  I just added some logic to partially consume the scroll event -- kinda works but not 100% reliable.  also working on a fix for scrollbars disappearing.

**Comment by rcoreilly** [comment]
ok fixed scrollbars disappearing.  there is still the "scroll grab" so if you want to scroll in a different dimension, you first have to do a non-scroll move of the mouse and then start scrolling the other way, only in this weird case where there are different levels.  sub-ideal but probably good for now.
